name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '26 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate

      - name: Lint PHP
        run: find src/ tests/ -name '*.php' -print0 | xargs -0 -n1 -P4 php -l >/dev/null

      - name: Install dependencies
        run: composer update

      - name: CGL check
        if: ${{ matrix.php == '7.2' }}
        run: vendor/bin/php-cs-fixer fix --dry-run

      - name: Phpstan
        if: ${{ matrix.php <= '8.0' }}
        run: vendor/bin/phpstan analyze --no-progress

      - name: Phpunit v8 and v9
        if: ${{ matrix.php <= '8.0' }}
        run: vendor/bin/phpunit -c phpunit-v9.xml.dist

      - name: Phpunit v10
        if: ${{ matrix.php >= '8.1' }}
        run: vendor/bin/phpunit
